package dev.chat.fork.messenger.jobs;

import android.app.Application;

import androidx.annotation.NonNull;

import dev.chat.fork.messenger.database.SignalDatabase;
import dev.chat.fork.messenger.jobmanager.Constraint;
import dev.chat.fork.messenger.jobmanager.ConstraintObserver;
import dev.chat.fork.messenger.jobmanager.Job;
import dev.chat.fork.messenger.jobmanager.JobMigration;
import dev.chat.fork.messenger.jobmanager.impl.AutoDownloadEmojiConstraint;
import dev.chat.fork.messenger.jobmanager.impl.BackupMessagesConstraint;
import dev.chat.fork.messenger.jobmanager.impl.BackupMessagesConstraintObserver;
import dev.chat.fork.messenger.jobmanager.impl.BatteryNotLowConstraint;
import dev.chat.fork.messenger.jobmanager.impl.ChangeNumberConstraint;
import dev.chat.fork.messenger.jobmanager.impl.ChangeNumberConstraintObserver;
import dev.chat.fork.messenger.jobmanager.impl.ChargingAndBatteryIsNotLowConstraintObserver;
import dev.chat.fork.messenger.jobmanager.impl.ChargingConstraint;
import dev.chat.fork.messenger.jobmanager.impl.DataRestoreConstraint;
import dev.chat.fork.messenger.jobmanager.impl.DataRestoreConstraintObserver;
import dev.chat.fork.messenger.jobmanager.impl.DecryptionsDrainedConstraint;
import dev.chat.fork.messenger.jobmanager.impl.DecryptionsDrainedConstraintObserver;
import dev.chat.fork.messenger.jobmanager.impl.DeletionNotAwaitingMediaDownloadConstraint;
import dev.chat.fork.messenger.jobmanager.impl.DiskSpaceNotLowConstraint;
import dev.chat.fork.messenger.jobmanager.impl.NetworkConstraint;
import dev.chat.fork.messenger.jobmanager.impl.NetworkConstraintObserver;
import dev.chat.fork.messenger.jobmanager.impl.NoRemoteArchiveGarbageCollectionPendingConstraint;
import dev.chat.fork.messenger.jobmanager.impl.NotInCallConstraint;
import dev.chat.fork.messenger.jobmanager.impl.NotInCallConstraintObserver;
import dev.chat.fork.messenger.jobmanager.impl.RegisteredConstraint;
import dev.chat.fork.messenger.jobmanager.impl.RestoreAttachmentConstraint;
import dev.chat.fork.messenger.jobmanager.impl.RestoreAttachmentConstraintObserver;
import dev.chat.fork.messenger.jobmanager.impl.SealedSenderConstraint;
import dev.chat.fork.messenger.jobmanager.impl.StickersNotDownloadingConstraint;
import dev.chat.fork.messenger.jobmanager.impl.WifiConstraint;
import dev.chat.fork.messenger.jobmanager.migrations.DeprecatedJobMigration;
import dev.chat.fork.messenger.jobmanager.migrations.DonationReceiptRedemptionJobMigration;
import dev.chat.fork.messenger.jobmanager.migrations.GroupCallPeekJobDataMigration;
import dev.chat.fork.messenger.jobmanager.migrations.PushDecryptMessageJobEnvelopeMigration;
import dev.chat.fork.messenger.jobmanager.migrations.PushProcessMessageJobMigration;
import dev.chat.fork.messenger.jobmanager.migrations.RetrieveProfileJobMigration;
import dev.chat.fork.messenger.jobmanager.migrations.SendReadReceiptsJobMigration;
import dev.chat.fork.messenger.jobmanager.migrations.SenderKeyDistributionSendJobRecipientMigration;
import dev.chat.fork.messenger.migrations.AccountConsistencyMigrationJob;
import dev.chat.fork.messenger.migrations.AccountRecordMigrationJob;
import dev.chat.fork.messenger.migrations.AepMigrationJob;
import dev.chat.fork.messenger.migrations.ApplyUnknownFieldsToSelfMigrationJob;
import dev.chat.fork.messenger.migrations.ArchiveBackupIdReservationMigrationJob;
import dev.chat.fork.messenger.migrations.AttachmentCleanupMigrationJob;
import dev.chat.fork.messenger.migrations.AttachmentHashBackfillMigrationJob;
import dev.chat.fork.messenger.migrations.AttributesMigrationJob;
import dev.chat.fork.messenger.migrations.AvatarColorStorageServiceMigrationJob;
import dev.chat.fork.messenger.migrations.AvatarIdRemovalMigrationJob;
import dev.chat.fork.messenger.migrations.AvatarMigrationJob;
import dev.chat.fork.messenger.migrations.BackfillCollapsedEventsMigrationJob;
import dev.chat.fork.messenger.migrations.BackfillDigestsForDuplicatesMigrationJob;
import dev.chat.fork.messenger.migrations.BackfillNotifiedStateMigrationJob;
import dev.chat.fork.messenger.migrations.BackupJitterMigrationJob;
import dev.chat.fork.messenger.migrations.BackupNotificationMigrationJob;
import dev.chat.fork.messenger.migrations.BadE164MigrationJob;
import dev.chat.fork.messenger.migrations.BlobStorageLocationMigrationJob;
import dev.chat.fork.messenger.migrations.CachedAttachmentsMigrationJob;
import dev.chat.fork.messenger.migrations.ClearGlideCacheMigrationJob;
import dev.chat.fork.messenger.migrations.ContactLinkRebuildMigrationJob;
import dev.chat.fork.messenger.migrations.CopyUsernameToSignalStoreMigrationJob;
import dev.chat.fork.messenger.migrations.DatabaseMigrationJob;
import dev.chat.fork.messenger.migrations.DeleteDeprecatedLogsMigrationJob;
import dev.chat.fork.messenger.migrations.DirectoryRefreshMigrationJob;
import dev.chat.fork.messenger.migrations.DuplicateE164MigrationJob;
import dev.chat.fork.messenger.migrations.E164FormattingMigrationJob;
import dev.chat.fork.messenger.migrations.EmojiDownloadMigrationJob;
import dev.chat.fork.messenger.migrations.EmojiSearchEnglishLabelsMigrationJob;
import dev.chat.fork.messenger.migrations.EmojiSearchIndexCheckMigrationJob;
import dev.chat.fork.messenger.migrations.FixChangeNumberErrorMigrationJob;
import dev.chat.fork.messenger.migrations.GooglePlayBillingPurchaseTokenMigrationJob;
import dev.chat.fork.messenger.migrations.GroupDeletedBackfillMigrationJob;
import dev.chat.fork.messenger.migrations.IdentityTableCleanupMigrationJob;
import dev.chat.fork.messenger.migrations.KeyTransparencyFailureMigrationJob;
import dev.chat.fork.messenger.migrations.KeyTransparencyUsernameMigrationJob;
import dev.chat.fork.messenger.migrations.LegacyMigrationJob;
import dev.chat.fork.messenger.migrations.LocalArchiveReconciliationMigrationJob;
import dev.chat.fork.messenger.migrations.MigrationCompleteJob;
import dev.chat.fork.messenger.migrations.OptimizeMessageSearchIndexMigrationJob;
import dev.chat.fork.messenger.migrations.PassingMigrationJob;
import dev.chat.fork.messenger.migrations.PinOptOutMigration;
import dev.chat.fork.messenger.migrations.PinReminderMigrationJob;
import dev.chat.fork.messenger.migrations.PniAccountInitializationMigrationJob;
import dev.chat.fork.messenger.migrations.PniMigrationJob;
import dev.chat.fork.messenger.migrations.PnpLaunchMigrationJob;
import dev.chat.fork.messenger.migrations.PreKeysSyncMigrationJob;
import dev.chat.fork.messenger.migrations.ProfileMigrationJob;
import dev.chat.fork.messenger.migrations.ProfileSharingUpdateMigrationJob;
import dev.chat.fork.messenger.migrations.QuoteThumbnailBackfillMigrationJob;
import dev.chat.fork.messenger.migrations.RebuildMessageSearchIndexMigrationJob;
import dev.chat.fork.messenger.migrations.RecheckPaymentsMigrationJob;
import dev.chat.fork.messenger.migrations.RecipientSearchMigrationJob;
import dev.chat.fork.messenger.migrations.ReleaseChannelRecipientFixMigrationJob;
import dev.chat.fork.messenger.migrations.ResetArchiveTierMigrationJob;
import dev.chat.fork.messenger.migrations.ResetKeyTransparencyMigrationJob;
import dev.chat.fork.messenger.migrations.SelfRegisteredStateMigrationJob;
import dev.chat.fork.messenger.migrations.StickerAdditionMigrationJob;
import dev.chat.fork.messenger.migrations.StickerDayByDayMigrationJob;
import dev.chat.fork.messenger.migrations.StickerLaunchMigrationJob;
import dev.chat.fork.messenger.migrations.StickerMyDailyLifeMigrationJob;
import dev.chat.fork.messenger.migrations.StickerPackAddition2MigrationJob;
import dev.chat.fork.messenger.migrations.StorageCapabilityMigrationJob;
import dev.chat.fork.messenger.migrations.StorageFixLocalUnknownMigrationJob;
import dev.chat.fork.messenger.migrations.StorageServiceMigrationJob;
import dev.chat.fork.messenger.migrations.StorageServiceSystemNameMigrationJob;
import dev.chat.fork.messenger.migrations.StoryViewedReceiptsStateMigrationJob;
import dev.chat.fork.messenger.migrations.SubscriberIdMigrationJob;
import dev.chat.fork.messenger.migrations.Svr2MirrorMigrationJob;
import dev.chat.fork.messenger.migrations.SyncCallLinksMigrationJob;
import dev.chat.fork.messenger.migrations.SyncChatFoldersMigrationJob;
import dev.chat.fork.messenger.migrations.SyncDistributionListsMigrationJob;
import dev.chat.fork.messenger.migrations.SyncKeysMigrationJob;
import dev.chat.fork.messenger.migrations.SyncStickerPacksMigrationJob;
import dev.chat.fork.messenger.migrations.TrimByLengthSettingsMigrationJob;
import dev.chat.fork.messenger.migrations.UpdateSmsJobsMigrationJob;
import dev.chat.fork.messenger.migrations.UserNotificationMigrationJob;
import dev.chat.fork.messenger.migrations.UuidMigrationJob;
import dev.chat.fork.messenger.migrations.WallpaperCleanupMigrationJob;
import dev.chat.fork.messenger.migrations.WallpaperStorageMigrationJob;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public final class JobManagerFactories {

  public static Map<String, Job.Factory> getJobFactories(@NonNull Application application) {
    return new HashMap<>() {{
      put(AccountConsistencyWorkerJob.KEY,             new AccountConsistencyWorkerJob.Factory());
      put(AdminDeleteSendJob.KEY,                      new AdminDeleteSendJob.Factory());
      put(AnalyzeDatabaseJob.KEY,                      new AnalyzeDatabaseJob.Factory());
      put(ApkUpdateJob.KEY,                            new ApkUpdateJob.Factory());
      put(ArchiveAttachmentBackfillJob.KEY,            new ArchiveAttachmentBackfillJob.Factory());
      put(ArchiveAttachmentReconciliationJob.KEY,      new ArchiveAttachmentReconciliationJob.Factory());
      put(ArchiveBackupIdReservationJob.KEY,           new ArchiveBackupIdReservationJob.Factory());
      put(ArchiveCommitAttachmentDeletesJob.KEY,       new ArchiveCommitAttachmentDeletesJob.Factory());
      put(ArchiveThumbnailBackfillJob.KEY,             new ArchiveThumbnailBackfillJob.Factory());
      put(ArchiveThumbnailUploadJob.KEY,               new ArchiveThumbnailUploadJob.Factory());
      put(AttachmentCompressionJob.KEY,                new AttachmentCompressionJob.Factory());
      put(AttachmentCopyJob.KEY,                       new AttachmentCopyJob.Factory());
      put(AttachmentDownloadJob.KEY,                   new AttachmentDownloadJob.Factory());
      put(AttachmentHashBackfillJob.KEY,               new AttachmentHashBackfillJob.Factory());
      put(AttachmentUploadJob.KEY,                     new AttachmentUploadJob.Factory());
      put(AutomaticSessionResetJob.KEY,                new AutomaticSessionResetJob.Factory());
      put(AvatarGroupsV1DownloadJob.KEY,               new AvatarGroupsV1DownloadJob.Factory());
      put(AvatarGroupsV2DownloadJob.KEY,               new AvatarGroupsV2DownloadJob.Factory());
      put(BackfillCollapsedMessageJob.KEY,             new BackfillCollapsedMessageJob.Factory());
      put(BackfillDigestsForDataFileJob.KEY,           new BackfillDigestsForDataFileJob.Factory());
      put(BackfillNotifiedStateJob.KEY,                new BackfillNotifiedStateJob.Factory());
      put(BackupDeleteJob.KEY,                         new BackupDeleteJob.Factory());
      put(BackupMessagesJob.KEY,                       new BackupMessagesJob.Factory());
      put(BackupRestoreMediaJob.KEY,                   new BackupRestoreMediaJob.Factory());
      put(BackupSubscriptionCheckJob.KEY,              new BackupSubscriptionCheckJob.Factory());
      put(BuildExpirationConfirmationJob.KEY,          new BuildExpirationConfirmationJob.Factory());
      put(CallingAssetsDownloadJob.KEY,                new CallingAssetsDownloadJob.Factory());
      put(CallLinkPeekJob.KEY,                         new CallLinkPeekJob.Factory());
      put(CallLinkUpdateSendJob.KEY,                   new CallLinkUpdateSendJob.Factory());
      put(CallLogEventSendJob.KEY,                     new CallLogEventSendJob.Factory());
      put(CallQualitySurveySubmissionJob.KEY,          new CallQualitySurveySubmissionJob.Factory());
      put(CallSyncEventJob.KEY,                        new CallSyncEventJob.Factory());
      put(CancelRestoreMediaJob.KEY,                   new CancelRestoreMediaJob.Factory());
      put(CheckKeyTransparencyJob.KEY,                 new CheckKeyTransparencyJob.Factory());
      put(CheckRestoreMediaLeftJob.KEY,                new CheckRestoreMediaLeftJob.Factory());
      put(CheckServiceReachabilityJob.KEY,             new CheckServiceReachabilityJob.Factory());
      put(CleanPreKeysJob.KEY,                         new CleanPreKeysJob.Factory());
      put(ConversationShortcutRankingUpdateJob.KEY,    new ConversationShortcutRankingUpdateJob.Factory());
      put(ConversationShortcutUpdateJob.KEY,           new ConversationShortcutUpdateJob.Factory());
      put(CopyAttachmentToArchiveJob.KEY,              new CopyAttachmentToArchiveJob.Factory());
      put(CreateReleaseChannelJob.KEY,                 new CreateReleaseChannelJob.Factory());
      put(DeleteAbandonedAttachmentsJob.KEY,           new DeleteAbandonedAttachmentsJob.Factory());
      put(DeprecatedNotificationJob.KEY,               new DeprecatedNotificationJob.Factory());
      put(DeviceNameChangeJob.KEY,                     new DeviceNameChangeJob.Factory());
      put(DirectoryRefreshJob.KEY,                     new DirectoryRefreshJob.Factory());
      put(DownloadLatestEmojiDataJob.KEY,              new DownloadLatestEmojiDataJob.Factory());
      put(E164FormattingJob.KEY,                       new E164FormattingJob.Factory());
      put(EmojiSearchIndexDownloadJob.KEY,             new EmojiSearchIndexDownloadJob.Factory());
      put(FcmRefreshJob.KEY,                           new FcmRefreshJob.Factory());
      put(FetchRemoteMegaphoneImageJob.KEY,            new FetchRemoteMegaphoneImageJob.Factory());
      put(FontDownloaderJob.KEY,                       new FontDownloaderJob.Factory());
      put(ForceUpdateGroupV2Job.KEY,                   new ForceUpdateGroupV2Job.Factory());
      put(ForceUpdateGroupV2WorkerJob.KEY,             new ForceUpdateGroupV2WorkerJob.Factory());
      put(GenerateAudioWaveFormJob.KEY,                new GenerateAudioWaveFormJob.Factory());
      put(GroupCallUpdateSendJob.KEY,                  new GroupCallUpdateSendJob.Factory());
      put(GroupCallPeekJob.KEY,                        new GroupCallPeekJob.Factory());
      put(GroupCallPeekWorkerJob.KEY,                  new GroupCallPeekWorkerJob.Factory());
      put(GroupDeletedBackfillWorkerJob.KEY,           new GroupDeletedBackfillWorkerJob.Factory());
      put(GroupRingCleanupJob.KEY,                     new GroupRingCleanupJob.Factory());
      put(GroupV2UpdateSelfProfileKeyJob.KEY,          new GroupV2UpdateSelfProfileKeyJob.Factory());
      put(InAppPaymentAuthCheckJob.KEY,                new InAppPaymentAuthCheckJob.Factory());
      put(InAppPaymentGiftSendJob.KEY,                 new InAppPaymentGiftSendJob.Factory());
      put(InAppPaymentKeepAliveJob.KEY,                new InAppPaymentKeepAliveJob.Factory());
      put(InAppPaymentPurchaseTokenJob.KEY,            new InAppPaymentPurchaseTokenJob.Factory());
      put(InAppPaymentRecurringContextJob.KEY,         new InAppPaymentRecurringContextJob.Factory());
      put(InAppPaymentOneTimeContextJob.KEY,           new InAppPaymentOneTimeContextJob.Factory());
      put(InAppPaymentRedemptionJob.KEY,               new InAppPaymentRedemptionJob.Factory());
      put(InAppPaymentPayPalOneTimeSetupJob.KEY,       new InAppPaymentPayPalOneTimeSetupJob.Factory());
      put(InAppPaymentPayPalRecurringSetupJob.KEY,     new InAppPaymentPayPalRecurringSetupJob.Factory());
      put(InAppPaymentStripeOneTimeSetupJob.KEY,       new InAppPaymentStripeOneTimeSetupJob.Factory());
      put(InAppPaymentStripeRecurringSetupJob.KEY,     new InAppPaymentStripeRecurringSetupJob.Factory());
      put(IndividualSendJob.KEY,                       new IndividualSendJob.Factory());
      put(IndividualSendJobV2.KEY,                     new IndividualSendJobV2.Factory());
      put(LeaveGroupV2Job.KEY,                         new LeaveGroupV2Job.Factory());
      put(LeaveGroupV2WorkerJob.KEY,                   new LeaveGroupV2WorkerJob.Factory());
      put(LinkedDeviceInactiveCheckJob.KEY,            new LinkedDeviceInactiveCheckJob.Factory());
      put(LocalArchiveJob.KEY,                         new LocalArchiveJob.Factory());
      put(LocalBackupJob.KEY,                          new LocalBackupJob.Factory());
      put(LocalPlaintextArchiveJob.KEY,                new LocalPlaintextArchiveJob.Factory());
      put(LocalBackupJobApi29.KEY,                     new LocalBackupJobApi29.Factory());
      put(MarkerJob.KEY,                               new MarkerJob.Factory());
      put(MessageSendLogCleanupJob.KEY,                new MessageSendLogCleanupJob.Factory());
      put(MultiDeviceAttachmentBackfillMissingJob.KEY, new MultiDeviceAttachmentBackfillMissingJob.Factory());
      put(MultiDeviceAttachmentBackfillRequestJob.KEY, new MultiDeviceAttachmentBackfillRequestJob.Factory());
      put(MultiDeviceAttachmentBackfillUpdateJob.KEY,  new MultiDeviceAttachmentBackfillUpdateJob.Factory());
      put(MultiDeviceBlockedUpdateJob.KEY,             new MultiDeviceBlockedUpdateJob.Factory());
      put(MultiDeviceCallLinkSyncJob.KEY,              new MultiDeviceCallLinkSyncJob.Factory());
      put(MultiDeviceConfigurationUpdateJob.KEY,       new MultiDeviceConfigurationUpdateJob.Factory());
      put(MultiDeviceContactSyncJob.KEY,               new MultiDeviceContactSyncJob.Factory());
      put(MultiDeviceContactUpdateJob.KEY,             new MultiDeviceContactUpdateJob.Factory());
      put(MultiDeviceDeleteSyncJob.KEY,                new MultiDeviceDeleteSyncJob.Factory());
      put(MultiDeviceKeysUpdateJob.KEY,                new MultiDeviceKeysUpdateJob.Factory());
      put(MultiDeviceMessageRequestResponseJob.KEY,    new MultiDeviceMessageRequestResponseJob.Factory());
      put(MultiDeviceOutgoingPaymentSyncJob.KEY,       new MultiDeviceOutgoingPaymentSyncJob.Factory());
      put(MultiDeviceProfileContentUpdateJob.KEY,      new MultiDeviceProfileContentUpdateJob.Factory());
      put(MultiDeviceProfileKeyUpdateJob.KEY,          new MultiDeviceProfileKeyUpdateJob.Factory());
      put(MultiDeviceReadUpdateJob.KEY,                new MultiDeviceReadUpdateJob.Factory());
      put(MultiDeviceStickerPackOperationJob.KEY,      new MultiDeviceStickerPackOperationJob.Factory());
      put(MultiDeviceStickerPackSyncJob.KEY,           new MultiDeviceStickerPackSyncJob.Factory());
      put(MultiDeviceStorageSyncRequestJob.KEY,        new MultiDeviceStorageSyncRequestJob.Factory());
      put(MultiDeviceSubscriptionSyncRequestJob.KEY,   new MultiDeviceSubscriptionSyncRequestJob.Factory());
      put(MultiDeviceUsernameChangeSyncJob.KEY,        new MultiDeviceUsernameChangeSyncJob.Factory());
      put(MultiDeviceVerifiedUpdateJob.KEY,            new MultiDeviceVerifiedUpdateJob.Factory());
      put(MultiDeviceViewOnceOpenJob.KEY,              new MultiDeviceViewOnceOpenJob.Factory());
      put(MultiDeviceViewedUpdateJob.KEY,              new MultiDeviceViewedUpdateJob.Factory());
      put(NewLinkedDeviceNotificationJob.KEY,          new NewLinkedDeviceNotificationJob.Factory());
      put(NullMessageSendJob.KEY,                      new NullMessageSendJob.Factory());
      put(OptimizeMediaJob.KEY,                        new OptimizeMediaJob.Factory());
      put(OptimizeMessageSearchIndexJob.KEY,           new OptimizeMessageSearchIndexJob.Factory());
      put(PaymentLedgerUpdateJob.KEY,                  new PaymentLedgerUpdateJob.Factory());
      put(PaymentNotificationSendJob.KEY,              new PaymentNotificationSendJob.Factory());
      put(PaymentNotificationSendJobV2.KEY,            new PaymentNotificationSendJobV2.Factory());
      put(PaymentSendJob.KEY,                          new PaymentSendJob.Factory());
      put(PaymentTransactionCheckJob.KEY,              new PaymentTransactionCheckJob.Factory());
      put(PollVoteJob.KEY,                             new PollVoteJob.Factory());
      put(PreKeysSyncJob.KEY,                          new PreKeysSyncJob.Factory());
      put(ProfileKeySendJob.KEY,                       new ProfileKeySendJob.Factory());
      put(ProfileUploadJob.KEY,                        new ProfileUploadJob.Factory());
      put(PushDistributionListSendJob.KEY,             new PushDistributionListSendJob.Factory());
      put(PushGroupSendJob.KEY,                        new PushGroupSendJob.Factory());
      put(PushGroupSilentUpdateSendJob.KEY,            new PushGroupSilentUpdateSendJob.Factory());
      put(MessageFetchJob.KEY,                         new MessageFetchJob.Factory());
      put(PostRegistrationBackupRedemptionJob.KEY,     new PostRegistrationBackupRedemptionJob.Factory());
      put(PushProcessEarlyMessagesJob.KEY,             new PushProcessEarlyMessagesJob.Factory());
      put(PushProcessMessageErrorJob.KEY,              new PushProcessMessageErrorJob.Factory());
      put(PushProcessMessageJob.KEY,                   new PushProcessMessageJob.Factory());
      put(QuoteThumbnailBackfillJob.KEY,               new QuoteThumbnailBackfillJob.Factory());
      put(QuoteThumbnailReconstructionJob.KEY,         new QuoteThumbnailReconstructionJob.Factory());
      put(ReactionSendJob.KEY,                         new ReactionSendJob.Factory());
      put(RebuildMessageSearchIndexJob.KEY,            new RebuildMessageSearchIndexJob.Factory());
      put(ReclaimUsernameAndLinkJob.KEY,               new ReclaimUsernameAndLinkJob.Factory());
      put(RefreshAttributesJob.KEY,                    new RefreshAttributesJob.Factory());
      put(RefreshCallLinkDetailsJob.KEY,               new RefreshCallLinkDetailsJob.Factory());
      put(RefreshDonationSubscriptionStatusJob.KEY,    new RefreshDonationSubscriptionStatusJob.Factory());
      put(RefreshSvrCredentialsJob.KEY,                new RefreshSvrCredentialsJob.Factory());
      put(RefreshOwnProfileJob.KEY,                    new RefreshOwnProfileJob.Factory());
      put(RemoteConfigRefreshJob.KEY,                  new RemoteConfigRefreshJob.Factory());
      put(RemoteDeleteSendJob.KEY,                     new RemoteDeleteSendJob.Factory());
      put(ReportSpamJob.KEY,                           new ReportSpamJob.Factory());
      put(ResendMessageJob.KEY,                        new ResendMessageJob.Factory());
      put(RequestGroupV2InfoWorkerJob.KEY,             new RequestGroupV2InfoWorkerJob.Factory());
      put(RequestGroupV2InfoJob.KEY,                   new RequestGroupV2InfoJob.Factory());
      put(LocalBackupRestoreMediaJob.KEY,              new LocalBackupRestoreMediaJob.Factory());
      put(RestoreAttachmentJob.KEY,                    new RestoreAttachmentJob.Factory());
      put(RestoreAttachmentThumbnailJob.KEY,           new RestoreAttachmentThumbnailJob.Factory());
      put(RestoreLocalAttachmentJob.KEY,               new RestoreLocalAttachmentJob.Factory());
      put(RestoreOptimizedMediaJob.KEY,                new RestoreOptimizedMediaJob.Factory());
      put(RetrieveProfileAvatarJob.KEY,                new RetrieveProfileAvatarJob.Factory());
      put(RetrieveProfileJob.KEY,                      new RetrieveProfileJob.Factory());
      put(RetrieveRemoteAnnouncementsJob.KEY,          new RetrieveRemoteAnnouncementsJob.Factory());
      put(RotateCertificateJob.KEY,                    new RotateCertificateJob.Factory());
      put(RotateProfileKeyJob.KEY,                     new RotateProfileKeyJob.Factory());
      put(SenderKeyDistributionSendJob.KEY,            new SenderKeyDistributionSendJob.Factory());
      put(SendDeliveryReceiptJob.KEY,                  new SendDeliveryReceiptJob.Factory());
      put(SendPaymentsActivatedJob.KEY,                new SendPaymentsActivatedJob.Factory());
      put(SendReadReceiptJob.KEY,                      new SendReadReceiptJob.Factory());
      put(SendRetryReceiptJob.KEY,                     new SendRetryReceiptJob.Factory());
      put(SendViewedReceiptJob.KEY,                    new SendViewedReceiptJob.Factory(application));
      put(StorageRotateManifestJob.KEY,                new StorageRotateManifestJob.Factory());
      put(SyncSystemContactLinksJob.KEY,               new SyncSystemContactLinksJob.Factory());
      put(MultiDeviceStorySendSyncJob.KEY,             new MultiDeviceStorySendSyncJob.Factory());
      put(ResetSvrGuessCountJob.KEY,                   new ResetSvrGuessCountJob.Factory());
      put(RetryPendingSendsJob.KEY,                    new RetryPendingSendsJob.Factory());
      put(RetryPendingSendSecondCheckJob.KEY,          new RetryPendingSendSecondCheckJob.Factory());
      put(ServiceOutageDetectionJob.KEY,               new ServiceOutageDetectionJob.Factory());
      put(StickerDownloadJob.KEY,                      new StickerDownloadJob.Factory());
      put(StickerPackDownloadJob.KEY,                  new StickerPackDownloadJob.Factory());
      put(StorageAccountRestoreJob.KEY,                new StorageAccountRestoreJob.Factory());
      put(StorageForcePushJob.KEY,                     new StorageForcePushJob.Factory());
      put(StorageSyncJob.KEY,                          new StorageSyncJob.Factory());
      put(StoryOnboardingDownloadJob.KEY,              new StoryOnboardingDownloadJob.Factory());
      put(SubmitRateLimitPushChallengeJob.KEY,         new SubmitRateLimitPushChallengeJob.Factory());
      put(Svr2MirrorJob.KEY,                           new Svr2MirrorJob.Factory());
      put(Svr3MirrorJob.KEY,                           new Svr3MirrorJob.Factory());
      put(ThreadUpdateJob.KEY,                         new ThreadUpdateJob.Factory());
      put(TrimThreadJob.KEY,                           new TrimThreadJob.Factory());
      put(TypingSendJob.KEY,                           new TypingSendJob.Factory());
      put(UnpinMessageJob.KEY,                         new UnpinMessageJob.Factory());
      put(UploadAttachmentToArchiveJob.KEY,            new UploadAttachmentToArchiveJob.Factory());

      // Migrations
      put(AccountConsistencyMigrationJob.KEY,             new AccountConsistencyMigrationJob.Factory());
      put(AccountRecordMigrationJob.KEY,                  new AccountRecordMigrationJob.Factory());
      put(AepMigrationJob.KEY,                            new AepMigrationJob.Factory());
      put(ApplyUnknownFieldsToSelfMigrationJob.KEY,       new ApplyUnknownFieldsToSelfMigrationJob.Factory());
      put(ArchiveBackupIdReservationMigrationJob.KEY,     new ArchiveBackupIdReservationMigrationJob.Factory());
      put(AttachmentCleanupMigrationJob.KEY,              new AttachmentCleanupMigrationJob.Factory());
      put(AttachmentHashBackfillMigrationJob.KEY,         new AttachmentHashBackfillMigrationJob.Factory());
      put(AttributesMigrationJob.KEY,                     new AttributesMigrationJob.Factory());
      put(AvatarColorStorageServiceMigrationJob.KEY,      new AvatarColorStorageServiceMigrationJob.Factory());
      put(AvatarIdRemovalMigrationJob.KEY,                new AvatarIdRemovalMigrationJob.Factory());
      put(AvatarMigrationJob.KEY,                         new AvatarMigrationJob.Factory());
      put(BackfillCollapsedEventsMigrationJob.KEY,        new BackfillCollapsedEventsMigrationJob.Factory());
      put(BackfillDigestsForDuplicatesMigrationJob.KEY,   new BackfillDigestsForDuplicatesMigrationJob.Factory());
      put(BackfillNotifiedStateMigrationJob.KEY,          new BackfillNotifiedStateMigrationJob.Factory());
      put(BackupJitterMigrationJob.KEY,                   new BackupJitterMigrationJob.Factory());
      put(BackupNotificationMigrationJob.KEY,             new BackupNotificationMigrationJob.Factory());
      put(BackupRefreshJob.KEY,                           new BackupRefreshJob.Factory());
      put(BadE164MigrationJob.KEY,                        new BadE164MigrationJob.Factory());
      put(BlobStorageLocationMigrationJob.KEY,            new BlobStorageLocationMigrationJob.Factory());
      put(CachedAttachmentsMigrationJob.KEY,              new CachedAttachmentsMigrationJob.Factory());
      put(ClearGlideCacheMigrationJob.KEY,                new ClearGlideCacheMigrationJob.Factory());
      put(ContactLinkRebuildMigrationJob.KEY,             new ContactLinkRebuildMigrationJob.Factory());
      put(CopyUsernameToSignalStoreMigrationJob.KEY,      new CopyUsernameToSignalStoreMigrationJob.Factory());
      put(DatabaseMigrationJob.KEY,                       new DatabaseMigrationJob.Factory());
      put(DeleteDeprecatedLogsMigrationJob.KEY,           new DeleteDeprecatedLogsMigrationJob.Factory());
      put(DirectoryRefreshMigrationJob.KEY,               new DirectoryRefreshMigrationJob.Factory());
      put(DuplicateE164MigrationJob.KEY,                  new DuplicateE164MigrationJob.Factory());
      put(E164FormattingMigrationJob.KEY,                 new E164FormattingMigrationJob.Factory());
      put(EmojiDownloadMigrationJob.KEY,                  new EmojiDownloadMigrationJob.Factory());
      put(EmojiSearchEnglishLabelsMigrationJob.KEY,       new EmojiSearchEnglishLabelsMigrationJob.Factory());
      put(EmojiSearchIndexCheckMigrationJob.KEY,          new EmojiSearchIndexCheckMigrationJob.Factory());
      put(FixChangeNumberErrorMigrationJob.KEY,           new FixChangeNumberErrorMigrationJob.Factory());
      put(GooglePlayBillingPurchaseTokenMigrationJob.KEY, new GooglePlayBillingPurchaseTokenMigrationJob.Factory());
      put(GroupDeletedBackfillMigrationJob.KEY,           new GroupDeletedBackfillMigrationJob.Factory());
      put(IdentityTableCleanupMigrationJob.KEY,           new IdentityTableCleanupMigrationJob.Factory());
      put(KeyTransparencyFailureMigrationJob.KEY,         new KeyTransparencyFailureMigrationJob.Factory());
      put(KeyTransparencyUsernameMigrationJob.KEY,        new KeyTransparencyUsernameMigrationJob.Factory());
      put(LegacyMigrationJob.KEY,                         new LegacyMigrationJob.Factory());
      put(LocalArchiveReconciliationMigrationJob.KEY,     new LocalArchiveReconciliationMigrationJob.Factory());
      put(MigrationCompleteJob.KEY,                       new MigrationCompleteJob.Factory());
      put(OptimizeMessageSearchIndexMigrationJob.KEY,     new OptimizeMessageSearchIndexMigrationJob.Factory());
      put(PinOptOutMigration.KEY,                         new PinOptOutMigration.Factory());
      put(PinReminderMigrationJob.KEY,                    new PinReminderMigrationJob.Factory());
      put(PniAccountInitializationMigrationJob.KEY,       new PniAccountInitializationMigrationJob.Factory());
      put(PniMigrationJob.KEY,                            new PniMigrationJob.Factory());
      put(PnpLaunchMigrationJob.KEY,                      new PnpLaunchMigrationJob.Factory());
      put(PreKeysSyncMigrationJob.KEY,                    new PreKeysSyncMigrationJob.Factory());
      put(ProfileMigrationJob.KEY,                        new ProfileMigrationJob.Factory());
      put(ProfileSharingUpdateMigrationJob.KEY,           new ProfileSharingUpdateMigrationJob.Factory());
      put(QuoteThumbnailBackfillMigrationJob.KEY,         new QuoteThumbnailBackfillMigrationJob.Factory());
      put(RebuildMessageSearchIndexMigrationJob.KEY,      new RebuildMessageSearchIndexMigrationJob.Factory());
      put(RecheckPaymentsMigrationJob.KEY,                new RecheckPaymentsMigrationJob.Factory());
      put(ReleaseChannelRecipientFixMigrationJob.KEY,     new ReleaseChannelRecipientFixMigrationJob.Factory());
      put(RecipientSearchMigrationJob.KEY,                new RecipientSearchMigrationJob.Factory());
      put(ResetArchiveTierMigrationJob.KEY,               new ResetArchiveTierMigrationJob.Factory());
      put(ResetKeyTransparencyMigrationJob.KEY,           new ResetKeyTransparencyMigrationJob.Factory());
      put(SelfRegisteredStateMigrationJob.KEY,            new SelfRegisteredStateMigrationJob.Factory());
      put(StickerLaunchMigrationJob.KEY,                  new StickerLaunchMigrationJob.Factory());
      put(StickerAdditionMigrationJob.KEY,                new StickerAdditionMigrationJob.Factory());
      put(StickerDayByDayMigrationJob.KEY,                new StickerDayByDayMigrationJob.Factory());
      put(StickerMyDailyLifeMigrationJob.KEY,             new StickerMyDailyLifeMigrationJob.Factory());
      put(StickerPackAddition2MigrationJob.KEY,           new StickerPackAddition2MigrationJob.Factory());
      put(StorageCapabilityMigrationJob.KEY,              new StorageCapabilityMigrationJob.Factory());
      put(StorageFixLocalUnknownMigrationJob.KEY,         new StorageFixLocalUnknownMigrationJob.Factory());
      put(StorageServiceMigrationJob.KEY,                 new StorageServiceMigrationJob.Factory());
      put(StorageServiceSystemNameMigrationJob.KEY,       new StorageServiceSystemNameMigrationJob.Factory());
      put(StoryViewedReceiptsStateMigrationJob.KEY,       new StoryViewedReceiptsStateMigrationJob.Factory());
      put(SubscriberIdMigrationJob.KEY,                   new SubscriberIdMigrationJob.Factory());
      put(Svr2MirrorMigrationJob.KEY,                     new Svr2MirrorMigrationJob.Factory());
      put(SyncCallLinksMigrationJob.KEY,                  new SyncCallLinksMigrationJob.Factory());
      put(SyncChatFoldersMigrationJob.KEY,                new SyncChatFoldersMigrationJob.Factory());
      put(SyncDistributionListsMigrationJob.KEY,          new SyncDistributionListsMigrationJob.Factory());
      put(SyncKeysMigrationJob.KEY,                       new SyncKeysMigrationJob.Factory());
      put(SyncStickerPacksMigrationJob.KEY,               new SyncStickerPacksMigrationJob.Factory());
      put(TrimByLengthSettingsMigrationJob.KEY,           new TrimByLengthSettingsMigrationJob.Factory());
      put(UpdateSmsJobsMigrationJob.KEY,                  new UpdateSmsJobsMigrationJob.Factory());
      put(UserNotificationMigrationJob.KEY,               new UserNotificationMigrationJob.Factory());
      put(UuidMigrationJob.KEY,                           new UuidMigrationJob.Factory());
      put(WallpaperCleanupMigrationJob.KEY,               new WallpaperCleanupMigrationJob.Factory());
      put(WallpaperStorageMigrationJob.KEY,               new WallpaperStorageMigrationJob.Factory());

      // Dead jobs
      put(FailingJob.KEY,                                new FailingJob.Factory());
      put(PassingMigrationJob.KEY,                       new PassingMigrationJob.Factory());
      put("PushContentReceiveJob",                       new FailingJob.Factory());
      put("AttachmentUploadJob",                         new FailingJob.Factory());
      put("MmsSendJob",                                  new FailingJob.Factory());
      put("RefreshUnidentifiedDeliveryAbilityJob",       new FailingJob.Factory());
      put("Argon2TestJob",                               new FailingJob.Factory());
      put("Argon2TestMigrationJob",                      new PassingMigrationJob.Factory());
      put("StorageKeyRotationMigrationJob",              new PassingMigrationJob.Factory());
      put("StorageSyncJob",                              new StorageSyncJob.Factory());
      put("WakeGroupV2Job",                              new FailingJob.Factory());
      put("LeaveGroupJob",                               new FailingJob.Factory());
      put("PushGroupUpdateJob",                          new FailingJob.Factory());
      put("RequestGroupInfoJob",                         new FailingJob.Factory());
      put("RotateSignedPreKeyJob",                       new PreKeysSyncJob.Factory());
      put("CreateSignedPreKeyJob",                       new PreKeysSyncJob.Factory());
      put("RefreshPreKeysJob",                           new PreKeysSyncJob.Factory());
      put("RecipientChangedNumberJob",                   new FailingJob.Factory());
      put("PushTextSendJob",                             new IndividualSendJob.Factory());
      put("MultiDevicePniIdentityUpdateJob",             new FailingJob.Factory());
      put("MultiDeviceGroupUpdateJob",                   new FailingJob.Factory());
      put("CallSyncEventJob",                            new FailingJob.Factory());
      put("RegistrationPinV2MigrationJob",               new FailingJob.Factory());
      put("KbsEnclaveMigrationWorkerJob",                new FailingJob.Factory());
      put("KbsEnclaveMigrationJob",                      new PassingMigrationJob.Factory());
      put("ClearFallbackKbsEnclaveJob",                  new FailingJob.Factory());
      put("PushDecryptJob",                              new FailingJob.Factory());
      put("PushDecryptDrainedJob",                       new FailingJob.Factory());
      put("PushProcessJob",                              new FailingJob.Factory());
      put("DecryptionsDrainedMigrationJob",              new PassingMigrationJob.Factory());
      put("MmsReceiveJob",                               new FailingJob.Factory());
      put("MmsDownloadJob",                              new FailingJob.Factory());
      put("SmsReceiveJob",                               new FailingJob.Factory());
      put("StoryReadStateMigrationJob",                  new PassingMigrationJob.Factory());
      put("GroupV1MigrationJob",                         new FailingJob.Factory());
      put("NewRegistrationUsernameSyncJob",              new FailingJob.Factory());
      put("SmsSendJob",                                  new FailingJob.Factory());
      put("SmsSentJob",                                  new FailingJob.Factory());
      put("MmsSendJobV2",                                new FailingJob.Factory());
      put("AttachmentUploadJobV2",                       new FailingJob.Factory());
      put("SubscriptionKeepAliveJob",                    new FailingJob.Factory());
      put("ExternalLaunchDonationJob",                   new FailingJob.Factory());
      put("BoostReceiptCredentialsSubmissionJob",        new FailingJob.Factory());
      put("SubscriptionReceiptCredentialsSubmissionJob", new FailingJob.Factory());
      put("DonationReceiptRedemptionJob",                new FailingJob.Factory());
      put("SendGiftJob",                                 new FailingJob.Factory());
      put("InactiveGroupCheckMigrationJob",              new PassingMigrationJob.Factory());
      put("AttachmentMarkUploadedJob",                   new FailingJob.Factory());
      put("BackupMediaSnapshotSyncJob",                  new FailingJob.Factory());
      put("PnpInitializeDevicesJob",                     new FailingJob.Factory());
      put("BackupRestoreJob",                            new FailingJob.Factory());
      put("BackfillDigestsMigrationJob",                 new PassingMigrationJob.Factory());
      put("BackfillDigestJob",                           new FailingJob.Factory());
      put("ResumableUploadSpecJob",                      new FailingJob.Factory());
    }};
  }

  public static Map<String, Constraint.Factory> getConstraintFactories(@NonNull Application application) {
    return new HashMap<String, Constraint.Factory>() {{
      put(NoRemoteArchiveGarbageCollectionPendingConstraint.KEY, new NoRemoteArchiveGarbageCollectionPendingConstraint.Factory());
      put(AutoDownloadEmojiConstraint.KEY,                       new AutoDownloadEmojiConstraint.Factory(application));
      put(BackupMessagesConstraint.KEY,                          new BackupMessagesConstraint.Factory(application));
      put(BatteryNotLowConstraint.KEY,                           new BatteryNotLowConstraint.Factory());
      put(ChangeNumberConstraint.KEY,                            new ChangeNumberConstraint.Factory());
      put(ChargingConstraint.KEY,                                new ChargingConstraint.Factory());
      put(DataRestoreConstraint.KEY,                             new DataRestoreConstraint.Factory());
      put(DecryptionsDrainedConstraint.KEY,                      new DecryptionsDrainedConstraint.Factory());
      put(DeletionNotAwaitingMediaDownloadConstraint.KEY,        new DeletionNotAwaitingMediaDownloadConstraint.Factory());
      put(DiskSpaceNotLowConstraint.KEY,                         new DiskSpaceNotLowConstraint.Factory());
      put(NetworkConstraint.KEY,                                 new NetworkConstraint.Factory(application));
      put("NetworkOrCellServiceConstraint",                      new NetworkConstraint.Factory(application));
      put("CellServiceConstraint",                               new NetworkConstraint.Factory(application));
      put(NotInCallConstraint.KEY,                               new NotInCallConstraint.Factory());
      put(RegisteredConstraint.KEY,                              new RegisteredConstraint.Factory());
      put(RestoreAttachmentConstraint.KEY,                       new RestoreAttachmentConstraint.Factory(application));
      put(SealedSenderConstraint.KEY,                            new SealedSenderConstraint.Factory());
      put(StickersNotDownloadingConstraint.KEY,                  new StickersNotDownloadingConstraint.Factory());
      put(WifiConstraint.KEY,                                    new WifiConstraint.Factory(application));
    }};
  }

  public static List<ConstraintObserver> getConstraintObservers(@NonNull Application application) {
    return Arrays.asList(new ChargingAndBatteryIsNotLowConstraintObserver(application),
                         new NetworkConstraintObserver(application),
                         new DecryptionsDrainedConstraintObserver(),
                         new NotInCallConstraintObserver(),
                         ChangeNumberConstraintObserver.INSTANCE,
                         DataRestoreConstraintObserver.INSTANCE,
                         RestoreAttachmentConstraintObserver.INSTANCE,
                         NoRemoteArchiveGarbageCollectionPendingConstraint.Observer.INSTANCE,
                         RegisteredConstraint.Observer.INSTANCE,
                         BackupMessagesConstraintObserver.INSTANCE,
                         DeletionNotAwaitingMediaDownloadConstraint.Observer.INSTANCE,
                         StickersNotDownloadingConstraint.Observer.INSTANCE,
                         SealedSenderConstraint.Observer.INSTANCE);
  }

  public static List<JobMigration> getJobMigrations(@NonNull Application application) {
    return Arrays.asList(new DeprecatedJobMigration(2),
                         new DeprecatedJobMigration(3),
                         new DeprecatedJobMigration(4),
                         new SendReadReceiptsJobMigration(SignalDatabase.messages()),
                         new DeprecatedJobMigration(6),
                         new RetrieveProfileJobMigration(),
                         new PushDecryptMessageJobEnvelopeMigration(),
                         new SenderKeyDistributionSendJobRecipientMigration(),
                         new PushProcessMessageJobMigration(),
                         new DonationReceiptRedemptionJobMigration(),
                         new GroupCallPeekJobDataMigration());
  }
}
