/*
 * Copyright 2025 Signal Messenger, LLC
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package org.signal.core.ui.compose.theme

import androidx.compose.material3.Typography
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

@Immutable
data class SignalTypography(
  val displayLarge: TextStyle,
  val displayMedium: TextStyle,
  val displaySmall: TextStyle,
  val headlineLarge: TextStyle,
  val headlineMedium: TextStyle,
  val headlineSmall: TextStyle,
  val titleLarge: TextStyle,
  val titleMedium: TextStyle,
  val titleSmall: TextStyle,
  val bodyLarge: TextStyle,
  val bodyMedium: TextStyle,
  val bodySmall: TextStyle,
  val labelLarge: TextStyle,
  val labelMedium: TextStyle,
  val labelSmall: TextStyle,
  val caption: TextStyle,
  val captionSmall: TextStyle,
  val messageBody: TextStyle,
  val messageBodyLarge: TextStyle,
  val messageFooter: TextStyle,
  val messageTimestamp: TextStyle,
  val messageSubject: TextStyle,
  val messageSystem: TextStyle,
  val composerInput: TextStyle,
  val composerHint: TextStyle,
  val composerLabel: TextStyle,
  val navigationLabel: TextStyle,
  val navigationActive: TextStyle,
  val navigationInactive: TextStyle,
  val buttonLarge: TextStyle,
  val buttonMedium: TextStyle,
  val buttonSmall: TextStyle,
  val toolbarTitle: TextStyle,
  val toolbarSubtitle: TextStyle,
  val toolbarAction: TextStyle,
  val settingsTitle: TextStyle,
  val settingsSubtitle: TextStyle,
  val settingsDescription: TextStyle,
  val settingsSectionHeader: TextStyle,
  val searchInput: TextStyle,
  val searchPlaceholder: TextStyle,
  val searchResultTitle: TextStyle,
  val searchResultSnippet: TextStyle,
  val dialogTitle: TextStyle,
  val dialogBody: TextStyle,
  val dialogAction: TextStyle,
  val notificationTitle: TextStyle,
  val notificationBody: TextStyle,
  val notificationTimestamp: TextStyle,
  val badge: TextStyle,
  val badgeLarge: TextStyle,
  val tabLabel: TextStyle,
  val tabLabelActive: TextStyle,
  val tabLabelInactive: TextStyle,
  val bottomSheetTitle: TextStyle,
  val bottomSheetSubtitle: TextStyle,
  val bottomSheetAction: TextStyle,
  val mediaTitle: TextStyle,
  val mediaCaption: TextStyle,
  val mediaOverlayText: TextStyle,
  val storyText: TextStyle,
  val storyCaption: TextStyle,
  val releaseNotesTitle: TextStyle,
  val releaseNotesBody: TextStyle,
  val chatGroupName: TextStyle,
  val chatGroupDescription: TextStyle,
  val chatGroupMember: TextStyle,
  val chatInviteText: TextStyle,
  val contactName: TextStyle,
  val contactSubtitle: TextStyle,
  val contactDetail: TextStyle,
  val profileName: TextStyle,
  val profileBio: TextStyle,
  val profileStatus: TextStyle,
  val backupTitle: TextStyle,
  val backupBody: TextStyle,
  val backupLabel: TextStyle,
  val errorTitle: TextStyle,
  val errorBody: TextStyle,
  val warningTitle: TextStyle,
  val warningBody: TextStyle,
  val deliveryStatus: TextStyle,
  val readReceipt: TextStyle,
  val emojiLarge: TextStyle,
  val emojiMedium: TextStyle,
  val emojiSmall: TextStyle,
  val code: TextStyle,
  val codeBlock: TextStyle
)

val LocalSignalTypography = staticCompositionLocalOf { signalTypography() }

internal fun signalTypography(): SignalTypography {
  val base = Typography()

  return SignalTypography(
    displayLarge = base.displayLarge.copy(fontSize = 36.sp, lineHeight = 44.sp, letterSpacing = 0.sp),
    displayMedium = base.displayMedium.copy(fontSize = 32.sp, lineHeight = 40.sp, letterSpacing = 0.sp),
    displaySmall = base.displaySmall.copy(fontSize = 28.sp, lineHeight = 36.sp, letterSpacing = 0.sp),
    headlineLarge = base.headlineLarge.copy(fontSize = 32.sp, lineHeight = 40.sp, letterSpacing = 0.sp),
    headlineMedium = base.headlineMedium.copy(fontSize = 28.sp, lineHeight = 36.sp, letterSpacing = 0.sp),
    headlineSmall = base.headlineSmall.copy(fontSize = 24.sp, lineHeight = 32.sp, letterSpacing = 0.sp),
    titleLarge = base.titleLarge.copy(fontSize = 22.sp, lineHeight = 28.sp, letterSpacing = 0.sp),
    titleMedium = base.titleMedium.copy(fontSize = 18.sp, lineHeight = 24.sp, letterSpacing = 0.sp),
    titleSmall = base.titleSmall.copy(fontSize = 16.sp, lineHeight = 22.sp, letterSpacing = 0.sp),
    bodyLarge = base.bodyLarge.copy(fontSize = 16.sp, lineHeight = 22.sp, letterSpacing = 0.sp),
    bodyMedium = base.bodyMedium.copy(fontSize = 14.sp, lineHeight = 20.sp, letterSpacing = 0.sp),
    bodySmall = base.bodySmall.copy(fontSize = 13.sp, lineHeight = 16.sp, letterSpacing = 0.sp),
    labelLarge = base.labelLarge.copy(fontSize = 14.sp, lineHeight = 20.sp, letterSpacing = 0.sp),
    labelMedium = base.labelMedium.copy(fontSize = 13.sp, lineHeight = 16.sp, letterSpacing = 0.sp),
    labelSmall = base.labelSmall.copy(fontSize = 12.sp, lineHeight = 16.sp, letterSpacing = 0.sp),
    caption = TextStyle(fontSize = 12.sp, lineHeight = 16.sp, letterSpacing = 0.02.sp),
    captionSmall = TextStyle(fontSize = 11.sp, lineHeight = 14.sp, letterSpacing = 0.02.sp),
    messageBody = base.bodyMedium,
    messageBodyLarge = base.bodyLarge,
    messageFooter = base.labelSmall,
    messageTimestamp = base.labelSmall,
    messageSubject = base.titleMedium,
    messageSystem = base.labelMedium,
    composerInput = base.bodyLarge,
    composerHint = base.bodyMedium,
    composerLabel = base.labelMedium,
    navigationLabel = base.labelSmall,
    navigationActive = base.labelMedium.copy(fontWeight = FontWeight.Medium),
    navigationInactive = base.labelMedium,
    buttonLarge = base.labelLarge.copy(fontWeight = FontWeight.Medium),
    buttonMedium = base.labelMedium.copy(fontWeight = FontWeight.Medium),
    buttonSmall = base.labelSmall.copy(fontWeight = FontWeight.Medium),
    toolbarTitle = base.titleLarge.copy(fontWeight = FontWeight.Medium),
    toolbarSubtitle = base.bodySmall,
    toolbarAction = base.bodySmall.copy(fontWeight = FontWeight.Medium),
    settingsTitle = base.titleMedium,
    settingsSubtitle = base.bodyMedium,
    settingsDescription = base.bodySmall,
    settingsSectionHeader = base.labelLarge.copy(fontWeight = FontWeight.Medium),
    searchInput = base.bodyLarge,
    searchPlaceholder = base.bodyMedium,
    searchResultTitle = base.titleSmall,
    searchResultSnippet = base.bodySmall,
    dialogTitle = base.titleLarge,
    dialogBody = base.bodyMedium,
    dialogAction = base.labelLarge.copy(fontWeight = FontWeight.Medium),
    notificationTitle = base.titleSmall.copy(fontWeight = FontWeight.Medium),
    notificationBody = base.bodySmall,
    notificationTimestamp = TextStyle(fontSize = 11.sp, lineHeight = 14.sp, letterSpacing = 0.sp),
    badge = base.labelSmall.copy(fontWeight = FontWeight.Bold),
    badgeLarge = base.labelMedium.copy(fontWeight = FontWeight.Bold),
    tabLabel = base.labelMedium,
    tabLabelActive = base.labelMedium.copy(fontWeight = FontWeight.Bold),
    tabLabelInactive = base.labelMedium,
    bottomSheetTitle = base.titleMedium.copy(fontWeight = FontWeight.Medium),
    bottomSheetSubtitle = base.bodySmall,
    bottomSheetAction = base.labelLarge.copy(fontWeight = FontWeight.Medium),
    mediaTitle = base.titleSmall,
    mediaCaption = TextStyle(fontSize = 12.sp, lineHeight = 16.sp, letterSpacing = 0.sp),
    mediaOverlayText = base.labelMedium,
    storyText = base.bodyLarge,
    storyCaption = base.bodySmall,
    releaseNotesTitle = base.titleLarge,
    releaseNotesBody = base.bodyMedium,
    chatGroupName = base.titleMedium.copy(fontWeight = FontWeight.Medium),
    chatGroupDescription = base.bodySmall,
    chatGroupMember = base.bodyMedium,
    chatInviteText = base.bodyMedium,
    contactName = base.titleSmall.copy(fontWeight = FontWeight.Medium),
    contactSubtitle = base.bodySmall,
    contactDetail = base.bodySmall,
    profileName = base.headlineMedium,
    profileBio = base.bodyMedium,
    profileStatus = base.bodySmall,
    backupTitle = base.titleMedium.copy(fontWeight = FontWeight.Medium),
    backupBody = base.bodyMedium,
    backupLabel = base.labelMedium,
    errorTitle = base.titleMedium.copy(fontWeight = FontWeight.Medium),
    errorBody = base.bodyMedium,
    warningTitle = base.titleMedium.copy(fontWeight = FontWeight.Medium),
    warningBody = base.bodyMedium,
    deliveryStatus = base.labelSmall,
    readReceipt = base.labelSmall,
    emojiLarge = TextStyle(fontSize = 24.sp, lineHeight = 28.sp, letterSpacing = 0.sp),
    emojiMedium = TextStyle(fontSize = 18.sp, lineHeight = 22.sp, letterSpacing = 0.sp),
    emojiSmall = TextStyle(fontSize = 14.sp, lineHeight = 18.sp, letterSpacing = 0.sp),
    code = TextStyle(fontSize = 13.sp, lineHeight = 18.sp, letterSpacing = 0.01.sp, fontFamily = FontFamily.Monospace),
    codeBlock = TextStyle(fontSize = 13.sp, lineHeight = 20.sp, letterSpacing = 0.01.sp, fontFamily = FontFamily.Monospace)
  )
}
